export const cardsBook = [
    [
        {
            id: 1,
            title: "Home in Breckenridge",
            price: 4445,
            rating: 4.95,
            img: "/assets/images/img01.jpg",
        },
        {
            id: 2,
            title: "Lake Cabin Retreat",
            price: 299,
            rating: 4.85,
            img: "/assets/images/img02.jpg",
        },
        {
            id: 3,
            title: "Mountain View Villa",
            price: 850,
            rating: 4.90,
            img: "/assets/images/img03.jpg",
        },
        {
            id: 4,
            title: "City Center Apartment",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Condo in Breckenridge",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Silverthorne",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Apartment in Vail",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Guest suite in Frisco",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 9,
            title: "Condo in Avon",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img09.jpg",
        },
    ],
    [
        {
            id: 1,
            title: "Home in Breckenridge",
            price: 4445,
            rating: 4.95,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 2,
            title: "Lake Cabin Retreat",
            price: 299,
            rating: 4.85,
            img: "/assets/images/img01.jpg",
        },
        {
            id: 3,
            title: "Mountain View Villa",
            price: 850,
            rating: 4.90,
            img: "/assets/images/img10.jpg",
        },
        {
            id: 4,
            title: "City Center Apartment",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Condo in Breckenridge",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img01.jpg",
        },
        {
            id: 6,
            title: "Home in Silverthorne",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Apartment in Vail",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Guest suite in Frisco",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 9,
            title: "Condo in Avon",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img09.jpg",
        },
    ],
    [
        {
            id: 1,
            title: "Home in Breckenridge",
            price: 4445,
            rating: 4.95,
            img: "/assets/images/img09.jpg",
        },
        {
            id: 2,
            title: "Lake Cabin Retreat",
            price: 299,
            rating: 4.85,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 3,
            title: "Mountain View Villa",
            price: 850,
            rating: 4.90,
            img: "/assets/images/img01.jpg",
        },
        {
            id: 4,
            title: "City Center Apartment",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Condo in Breckenridge",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Silverthorne",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Apartment in Vail",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Guest suite in Frisco",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 9,
            title: "Condo in Avon",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img09.jpg",
        },
    ],
    [
        {
            id: 1,
            title: "Home in Breckenridge",
            price: 4445,
            rating: 4.95,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 2,
            title: "Lake Cabin Retreat",
            price: 299,
            rating: 4.85,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 3,
            title: "Mountain View Villa",
            price: 850,
            rating: 4.90,
            img: "/assets/images/img09.jpg",
        },
        {
            id: 4,
            title: "City Center Apartment",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Condo in Breckenridge",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Silverthorne",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Apartment in Vail",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Guest suite in Frisco",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 9,
            title: "Condo in Avon",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img09.jpg",
        },
    ],
    [
        {
            id: 1,
            title: "Home in Breckenridge",
            price: 4445,
            rating: 4.95,
            img: "/assets/images/img10.jpg",
        },
        {
            id: 2,
            title: "Lake Cabin Retreat",
            price: 299,
            rating: 4.85,
            img: "/assets/images/img09.jpg",
        },
        {
            id: 3,
            title: "Mountain View Villa",
            price: 850,
            rating: 4.90,
            img: "/assets/images/img03.jpg",
        },
        {
            id: 4,
            title: "City Center Apartment",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Condo in Breckenridge",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Silverthorne",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Apartment in Vail",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Guest suite in Frisco",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 9,
            title: "Condo in Avon",
            price: 150,
            rating: 4.78,
            img: "/assets/images/img09.jpg",
        },
    ],

];