export const cards = [
    [
        {
            id: 1,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img01.jpg",
        },
        {
            id: 2,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img02.jpg",
        },
        {
            id: 3,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img03.jpg",
        },
        {
            id: 4,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img08.jpg",
        }
    ], [
        {
            id: 1,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img10.jpg",
        },
        {
            id: 2,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img09.jpg",
        },
        {
            id: 3,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 4,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img08.jpg",
        }
    ], [
        {
            id: 1,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img10.jpg",
        },
        {
            id: 2,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img09.jpg",
        },
        {
            id: 3,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img08.jpg",
        },
        {
            id: 4,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img04.jpg",
        },
        {
            id: 5,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img05.jpg",
        },
        {
            id: 6,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img06.jpg",
        },
        {
            id: 7,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img07.jpg",
        },
        {
            id: 8,
            title: "Home in Breckenridge",
            rating: 4.95,
            price: 4445,
            img: "/assets/images/img08.jpg",
        }
    ]
];